name: 🚀 Deploy via SSH para Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Executando git pull no servidor via SSH
    runs-on: ubuntu-latest

    steps:
      - name: 🔑 Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 🚀 Deploy no servidor Hostinger
        run: |
          ssh -o StrictHostKeyChecking=no -p 65002 u507148490@ssh.sustainatrip.tur.br "cd public_html && git pull origin main"
